#pragma once


#define DRIVE_CONF_HOLONOMIC
//#define DRIVE_CONF_DIFFERENTIAL


#define ENCODERS_RATE 500.0
#define CONTROL_RATE   200.0

#define ENCODERS_PERIOD (1000.0 / ENCODERS_RATE)
#define CONTROL_PERIOD (1000.0 / CONTROL_RATE)


#define PERIOD_CONTROL_REPORT 100  // ms
